"""initial migration

Revision ID: 1f1031188527
Revises: 237ab55691c9
Create Date: 2024-11-19 17:07:40.399758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1031188527'
down_revision: Union[str, None] = '237ab55691c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('abc_test', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'abc_test')
    # ### end Alembic commands ###
